### ISSUE TITLE
SyntaxError for both python3 and python2

### ISSUE THREAD

**Issue by ankur-gupta** [mitotic/graphterm#12]
GraphTerm is exactly the tool I was looking for. Sadly, I encounter this error when installing. Am I doing something wrong?

```bash
$ pip3 install --user --no-cache-dir graphterm
Collecting graphterm
  Downloading https://files.pythonhosted.org/packages/99/18/e8fb547adb0ed693ca332df62bf91d30216ba2d02c39c0e6d89df3fec792/graphterm-0.57.0.tar.gz (2.0MB)
    100% |████████████████████████████████| 2.0MB 11.6MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/g_/yk9s1qwn2fl0sgdjgs0zk9dh0000gn/T/pip-install-r66r3h0l/graphterm/setup.py", line 24
        except Exception, excp:
                        ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/g_/yk9s1qwn2fl0sgdjgs0zk9dh0000gn/T/pip-install-r66r3h0l/graphterm/
```

I am on a MacOS High Sierra. This is my `pip` and `python` version:
```bash
$ pip3 --version
pip 18.0 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
```

I tried this for python2 and I got somewhat different results. The installation succeeds but I cannot run the `gtermserver`. 

```bash
$ pip2 install --user graphterm
Collecting graphterm
  Downloading https://files.pythonhosted.org/packages/99/18/e8fb547adb0ed693ca332df62bf91d30216ba2d02c39c0e6d89df3fec792/graphterm-0.57.0.tar.gz (2.0MB)
    100% |████████████████████████████████| 2.0MB 5.5MB/s
Requirement already satisfied: tornado in ./Library/Python/2.7/lib/python/site-packages (from graphterm) (5.0.2)
Requirement already satisfied: backports-abc>=0.4 in ./Library/Python/2.7/lib/python/site-packages (from tornado->graphterm) (0.5)
Requirement already satisfied: futures in ./Library/Python/2.7/lib/python/site-packages (from tornado->graphterm) (3.2.0)
Requirement already satisfied: singledispatch in ./Library/Python/2.7/lib/python/site-packages (from tornado->graphterm) (3.4.0.3)
Requirement already satisfied: six in ./Library/Python/2.7/lib/python/site-packages (from singledispatch->tornado->graphterm) (1.11.0)
Building wheels for collected packages: graphterm
  Running setup.py bdist_wheel for graphterm ... done
  Stored in directory: /Users/ankur/Library/Caches/pip/wheels/05/15/0d/707b17f2bf05d5d4ff220536b80d7de606b64c73a4e17933d4
Successfully built graphterm
Installing collected packages: graphterm
Successfully installed graphterm-0.57.0
```

```bash
$ gtermserver --terminal --auth_type=none
Traceback (most recent call last):
  File "/Users/ankur/Library/Python/2.7/bin/gtermserver", line 7, in <module>
    from graphterm.gtermserver import main
  File "/Users/ankur/Library/Python/2.7/lib/python/site-packages/graphterm/gtermserver.py", line 46, in <module>
    import gtermhost
  File "/Users/ankur/Library/Python/2.7/lib/python/site-packages/graphterm/gtermhost.py", line 38, in <module>
    from tornado.tcpserver import TCPServer   # Tornado 3.0+
  File "/Users/ankur/Library/Python/2.7/lib/python/site-packages/tornado/tcpserver.py", line 23, in <module>
    from tornado import gen
  File "/Users/ankur/Library/Python/2.7/lib/python/site-packages/tornado/gen.py", line 100, in <module>
    from tornado.concurrent import (Future, is_future, chain_future, future_set_exc_info,
  File "/Users/ankur/Library/Python/2.7/lib/python/site-packages/tornado/concurrent.py", line 47, in <module>
    import asyncio
  File "/Users/ankur/Library/Python/2.7/lib/python/site-packages/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/Users/ankur/Library/Python/2.7/lib/python/site-packages/asyncio/selectors.py", line 39
    "{!r}".format(fileobj)) from None
                               ^
SyntaxError: invalid syntax
```

**Comment by Happy-Ferret** [comment]
Weird that it's trying to use asyncio.
I don't have that on my system (albeit, I currently use WSL. Haven't booted up my Mac in quite a while).
